[pytest]
# Tell pytest where the source code is
pythonpath = .

# Look for tests in this folder
testpaths = tests

# Auto-handle async functions (critical for FastAPI/Redis)
asyncio_mode = auto

# Default flags: verbose output and coverage report
addopts = -v --cov=app --cov-report=term-missing
asyncio_default_test_loop_scope = session