"""add createat to subscription model

Revision ID: ae0eecbafb13
Revises: 9ce46e19a651
Create Date: 2026-04-02 13:07:19.995636

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ae0eecbafb13"
down_revision: Union[str, Sequence[str], None] = "9ce46e19a651"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Add the column as nullable first
    op.add_column("subscriptions", sa.Column("is_active", sa.Boolean(), nullable=True))

    # 2. Update existing rows to have a default value (True)
    op.execute("UPDATE subscriptions SET is_active = True")

    # 3. Now that no rows are NULL, alter the column to be NOT NULL
    op.alter_column("subscriptions", "is_active", nullable=False)

    # Add your created_at column here as well (if not already there)
    op.add_column(
        "subscriptions",
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("subscriptions", "created_at")
    op.drop_column("subscriptions", "is_active")
    # ### end Alembic commands ###
